name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          # Define image name and lowercase it
          IMAGE_ID="ghcr.io/${{ github.repository }}"
          IMAGE_ID=$(echo "$IMAGE_ID" | tr '[:upper:]' '[:lower:]')

          # Define tags
          TAG_LATEST="latest"
          TAG_SHA="sha-${GITHUB_SHA::7}"  # first 7 chars of commit SHA

          echo "Building Docker image: $IMAGE_ID:$TAG_LATEST and $IMAGE_ID:$TAG_SHA"

          # Build image
          docker build -t $IMAGE_ID:$TAG_LATEST -t $IMAGE_ID:$TAG_SHA .

          # Push both tags
          docker push $IMAGE_ID:$TAG_LATEST
          docker push $IMAGE_ID:$TAG_SHA

      # Step 4: Verify images
      - name: List images
        run: docker images
